sudo: true
dist: trust
language: eneric

addons:
  apt:
    packages:
      - snapd

install:
  - sudo snap install hugo
  - export PATH=/snap/bin:$PATH

script: hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  target_branch: gh_pages
